version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      # Mount these if you need to make changes to the nginx config without rebuilding
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Uncomment for development (though using do.sh would be better for dev)
      # - ./src:/app/src
      # - ./docs:/app/docs
      # - ./blog:/app/blog
      # - ./static:/app/static
    restart: unless-stopped 