version: '3.8'

services:
  offers:
    image: rediacc/offers:latest
    container_name: offers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped 